### ISSUE TITLE
GUI zu Auswahl-Trial zu groß

### ISSUE THREAD

**Issue by sar-sturm** [weichware10/analyse#21]
Bei dem Auswahl-Trial Fenster kann ich die unteren Buttons nicht sehen und anklicken, da sie unter meiner Leiste versteckt sind. Ich kann die größe des Fensters auch nicht ändern und es auch nicht weit genug nach oben schieben um an die Buttons zu kommen

![image](https://user-images.githubusercontent.com/83303430/151626591-555fb16c-9d68-45f0-9557-b114627b86ef.png)

**Comment by joshuajeschek** [comment]
Interessant, danke! Ich arbeite an einem fix

**Comment by sar-sturm** [comment]
Hab grade gemerkt es ist bei allen Fenstern so, allerdings könnte das auch an meinem bescheidenen Laptop und seiner 1366 x 768 Bildschirmauflösung liegen

**Comment by joshuajeschek** [comment]
ja das ist klar das es daran liegt
what the fuck wieso wird sowas noch hergestellt
führt es noch wo anders zu usability beeinträchtigung?

**Comment by joshuajeschek** [comment]
bei configurator wahrscheinlich, oder?

**Comment by sar-sturm** [comment]
das ding ist schon ein paar jahre alt uff. ich schau gleich mal wegen der anderen sachen

**Comment by sar-sturm** [comment]
laut joni müsste unten noch ein zurück hin

![image](https://user-images.githubusercontent.com/83303430/151628564-9512116d-0d3b-4bab-b3f9-8a20d3fb8807.png)

**Comment by sar-sturm** [comment]
![image](https://user-images.githubusercontent.com/83303430/151628746-90f8d9db-695f-4ff1-9ca4-c54ac29cec10.png)

**Comment by sar-sturm** [comment]
Okay, nach ziemlich viel rumziehen Konnte ich bei Trialerstellung doch den vollen Bildschirm bekommen. Aber so nach oben verrutscht sieht alles am Anfang aus, nur bei den anderen Fenstern kann ich nicht genug ziehen

**Comment by joshuajeschek** [comment]
ich habe einen neuen branch geöffnet, trial selector dürfte gehen bei dir jetzt
